name: ESLint + SARIF Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  eslint-scan:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # or your Next.js version

      # 3️⃣ Install dependencies (including eslint-formatter-sarif)
      - name: Install dependencies
        run: |
          npm install
          npm install -D eslint-formatter-sarif

      # 4️⃣ Run ESLint and generate SARIF
      - name: Run ESLint (SARIF)
        run: |
          npx eslint "src/**/*.{js,jsx,ts,tsx}" \
            -f node_modules/eslint-formatter-sarif/eslint-formatter-sarif.js \
            -o eslint-results.sarif

      # 5️⃣ Upload SARIF to GitHub Code Scanning
      - name: Upload ESLint SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
